name: Run Tests
on: 
  push:
    branches: [ main, master ]
jobs:
  api-tests:
      runs-on: ubuntu-latest
      steps: 
        - uses: actions/checkout@v4
        - name: Setup dotnet
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 8.0.x
        - name: Running API Tests
          working-directory: ./RecipeManager.API.Tests
          run: dotnet test
